### ISSUE TITLE
Missing import

### ISSUE THREAD

**Issue by Robbie1977** [simonjupp/urigen#4]
import uk.ac.ebi.fgpt.urigen.web.view.UserNotFoundException missing in UrigenUserController

**Comment by simonjupp** [comment]
Just pushed some changes, I've had to do some work to replace the persona open id login with github since the persona project is now deprecated. You'll need to make some additional changes to get that working. Ping me if you need some help.

**Comment by Robbie1977** [comment]
Thanks that fixed the build.
Now getting issues with it referring to http://garfield.ebi.ac.uk:8180/ inspite of the configured API code and URL as per https://github.com/simonjupp/urigen/wiki/GitHub-login

**Comment by Robbie1977** [comment]
This line has you client ID hard coded: https://github.com/simonjupp/urigen/blob/c691506d4d0187860d6ca80a2b5bcd2a2df8254e/urigen-core/src/main/webapp/scripts/urigen-login.js#L90

**Comment by simonjupp** [comment]
This is also fixed now.

**Comment by Robbie1977** [comment]
All running but doesn't seem to add the first user as admin as it did with persona.
Getting ```User not registered, please contact an admin```
server is here: http://vfb-karenin.inf.ed.ac.uk/urigen/
Have cleared the DB files and restarted but still get the same.

**Comment by simonjupp** [comment]
OK, last push should hopefully have fixed that. Not thoroughly tested tho!

**Comment by Robbie1977** [comment]
Great Thanks
